version: '1'

services:
    python:
        image: python:3.8
        volumes:
            - ./emart23:/emart23
        ports:
            - 8000:8000
        command: bash -c "cd ./emart23 && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"